version: '3.8'

services:

  mongodb:
    image: mongo:7.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./dump:/dump

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017/

  bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    image: bot
    command: python run.py
    env_file:
      - ./.env
    depends_on:
      - mongodb